data ={
    "Exam Fee":{
        "INDIAN":{
            "ALL_COURSES":{
                    "ALL_LEVEL":
                    {
                    "amount":400,
                    "Gst":18
                    }
            }
        },
        "FOREIGN":{
            "ALL_COURSES":{
                "ALL_LEVEL":{
                "amount":100,
                "Gst":28
                }
            }
        },
        "NRI":{
            "ALL_COURSES":{
                "ALL_LEVEL":{
                    "amount":600,
                    "Gst":28
                }
            }
        },
        "SAARC":{
            "ALL_COURSES":{
               "ALL_LEVEL":{
                    "amount":600,
                    "Gst":18
                }
            }
        }
     },
     "Application Fee":{
        "INDIAN":{
            "ALL_COURSES":{
                "UG":{
                    "amount":200,
                    "Gst":18
                },
                "UG-DIPLOMA":{
                "amount":300,
                "Gst":18
                },
                "PG":{
                "amount":500,
                "Gst":18
                }
            }
            
        },
        "FOREIGN":{
            "ALL_COURSES":{
                "UG":{
                    "amount":400,
                    "Gst":28
                },
                "UG-DIPLOMA":{
                    "amount":400,
                    "Gst":28
                },
                "PG":{
                    "amount":700,
                    "Gst":28
                }
            }
        }
    }
}